### ISSUE TITLE
Preannouncement messages are not displayed correctly

### ISSUE THREAD

**Issue by borisbergman** [borisbergman/EscInstaller#34]

**Comment by RamonZwaga** [comment]
Still not clear (from the start) how track ID's are stored and how these should be selected. Note: open FW items is pre-anouncement for the 'external audio input'. If this is fixed in the FW it should also be fixed in the GUI SW

**Comment by hoherprotektor** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19922934/23506153/16b1a586-ff47-11e6-9d0a-aa913849703e.png)

When downloading Mp3 from the System the order is messed up.

**Comment by borisbergman** [comment]
Please provide me a few feedback's of a esc with selected messages. I'll make sure the software works correct for those cases.

**Comment by hoherprotektor** [comment]
Here is what I tested so far. Byte send from unit here is the Alarm 1 track for Button or file programming and choosing Alarm 1 under Alarm 1- Settings 
![grafik](https://cloud.githubusercontent.com/assets/19922934/25133177/2feb8376-244c-11e7-95d2-9e7b5565fc98.png)

**Comment by hoherprotektor** [comment]
for better understanding: 0_2Ala~( is there a better way to show this) should stand on the first position, because the 16kHz shouldn't be available.  254 and 255 mustn't be FF. FF is for 255. But this should be done for by only using  250 tracks.  what does the ~1 mean?

**Comment by borisbergman** [comment]
file names with ~1 is what happens when the name is longer than 8 chars. This what comes out of the vs1053 chip.

**Comment by hoherprotektor** [comment]
The counting is ok. 02_ALA~1 should stand on the position of the orange "1" which is also in column 3 in the picture. After download the files, the files are the same I ulploaded before, so this is also fine. 
If i don't readout the sd track names and only use the orange ones. everting is fine. But when I click "0_2ALA~1" then 08_Testtrack is played. When i press 03_ALA~1, 09_threeTone is played and so on.

**Comment by hoherprotektor** [comment]
// *** BU-AMP-Installation

// for extension board 1 to 3
// bit 0 --> bu-amp at extension board 1 installed  
// bit 1 --> bu-amp at extension board 2 installed
// bit 2 --> bu-amp at extension board 3 installed

**Comment by hoherprotektor** [comment]
![defaultmessage](https://cloud.githubusercontent.com/assets/19922934/25229104/42ef4618-25cf-11e7-8405-038184ccd3bd.JPG)

The default messages should be also 1 and 2.

**Comment by borisbergman** [comment]
What does "default message" mean? The selection represends the list of message numbers of the esc. As discussed earlier the shifing is already O.K., also for the ABCD buttons.

**Comment by hoherprotektor** [comment]
1 and 2 (orange) are typically alarm 1 and alarm 2. so it  was in earlier version of the installer Software. So there must be Alarmmessage 1    1 , and Alarmmessage 2  2. Order is ok, like i said.

**Comment by borisbergman** [comment]
We don't deal with "earlier versions" of the installer software, who's gonna find out which version and what logic was applied? Neither do we know if it were correct. 

Question is: Apart from adjusting the message names, does selecting a message give the right result? Is downloading the message selection (again, apart from the names) showing the expected selections?

**Comment by RamonZwaga** [comment]
We tested the track selection (positions) and that seems ok; but the tracknames displayed in the dropdown  are not OK!!! What goes wrong with downloading the msg names and linking these to the correct position??

**Comment by borisbergman** [comment]
This question is for whom exactly?

**Comment by hoherprotektor** [comment]
for you.

**Comment by borisbergman** [comment]
In the phone call the messages were in the correct order. After the phone call you posted "The default messages should be also 1 and 2". So what is it going to be? Try to describe in such a way no misunderstanding can occur. Or better, try to adjust the emulator. We can also do this together.

**Comment by hoherprotektor** [comment]
ok again. grafik

**Comment by borisbergman** [comment]
1 Yes.
2. No.
2a. This is downloaded from the esc isn't it? 
2b. The same translation esc response to message number is applied as for the abcd buttons. Should a different shifting be applied?

**Comment by hoherprotektor** [comment]
2.a. i don't think so because then it would be 1 and 2(or in Textform 02Ala~1 and 03Ala~1).  Also when you open an default file it should be 1 and 2 (not 3 and 4). because stadard Alarms are 1 and 2.
2b. We have no problem with Shifting at all. When i select orange 1 then 1 is played, so this is ok.
We only have the problem descibed in picture two.

**Comment by hoherprotektor** [comment]
clear?

**Comment by borisbergman** [comment]
done

**Comment by hoherprotektor** [comment]
not done Standart text is still 3 and 4. Should be 1 and 2. 

![image](https://user-images.githubusercontent.com/19922934/33549094-aad3eefa-d8e9-11e7-8406-7bbf507553d4.png)

**Comment by RamonZwaga** [comment]
@hoherprotektor 
Michael, according to Boris this goes wrong on our side, please confirm!

**Comment by hoherprotektor** [comment]
I don't think so. This part isn't read out. This is only Predefined by the installer. Default is 1 and 2, even if there is no ECU connected this should be orange 1 +2 like in the Matrixselection.  Thats because on our SD Card this is also default. Only if those tracks are changed in the Installer then they can vary. 16kHz track should not be choosable(this is pysically on place 1.) In the Matrix this is implemented (see picture from the 18th april).  Only in this panel part it is wrong.

**Comment by RamonZwaga** [comment]
to both: why are the mp3 track names still not properly displayed?
the order of the tracks may be solved, but i just see numbers...

Is the default Alarm 1 & 2 track now 1 & 2 (and not 3&4)?

**Comment by borisbergman** [comment]
This is stored in the design file. When creating a new design message 1 and 2 respectively are now selected.

**Comment by RamonZwaga** [comment]
Seems ok now.
But tracknames still are not displayed > after talking with Michael there seem to be issues to ensure a correct transmission/storage of these names, but in order to be able to show the tracknames I have the following idea:

Question first: Instead of reading them from the eprom: can you also read the names from a txt.file?

Idea:
1) as the default tracks stored on the SD cards are known, we could provide a txt file (called defaultMP3.txt) which shows these. When opening the installer SW, you open this list to indicate the track names.
2) when the DIR-MP3 tool is used to change messages on the cards, we can create a new txt file (with different name) which now shows the actual mp3 overview of those cards: in the installer SW, when opening the 'alarm text' dropdowns, one first needs to select the correct mp3.txt file (in order to display the correct mp3 listing; for example by another (new) dropdown button which shows all these txt files (e.g. stored in the folder of this dir.mp3 tool)). Is this possible? Can this new created mp3.txt file also be linked to a design file?

**Comment by RamonZwaga** [comment]
Re-open after all other issues have been solved, but first discuss the options with Boris (time needed)!
